### ISSUE TITLE
Approach on event bubbling/preventDefault

### ISSUE THREAD

**Issue by jschilli** [emberjs-addons/ember-touch#13]
With ember master now dealing with return values from event handlers, ember-touch breaks in a way that is difficult to work around.

With two potentially overlapping views, both of which handle tapEnd for instance, the current implementation will trigger on both views.

It seems to me that this can be fixed in one of two ways.
1. have touch{End,Cancel,Start} do the right thing and return true/false when the handler returns - currently it is 'undefined' - 

or 
1. have attemptGestureDelivery and notifyViewOfGestureEvent pass the event into the gesture handler (e.g. tapEnd(recognizer,evt) 

The 2nd approach would put control over calling preventDefault() in the hands of the view handling the event.  

Either approach would work (I've implemented both and am currently using the 2nd approach with a fork of ember-touch)

Thoughts on a preferred way to handle this?

**Comment by ppcano** [comment]
I am still using 0.9.8.1, so i have still not experienced any problems. In order to advance development and support multiple ember versions, i have prepared the test suite to [be run with multiple ember versions](https://github.com/emberjs-addons/sproutcore-touch/#unit-tests).

Regarding your proposals, i think we should follow/continue ember approach.

1) Second option, makes sense to me, so far the view can also access the event on other browser events ( click ....) and allow to use preventDefault/stopPropagation on the view to manage App UI logic. I think this feature just extend the api and does not break anything.

2) [Event Bubbling is documented](http://emberjs.com/guides/view_layer/#toc_event-bubbling) and the code can be easily read at the [EventDispatcher](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/system/event_dispatcher.js).

The EventDispatcher executes the event stopPropagation method when it is handled with an eventManagers and does not bubble up it.

That's why bubbling up is done with the [gestureManager](https://github.com/emberjs-addons/sproutcore-touch/blob/master/packages/ember-touch/lib/system/gesture_manager.js#L142).

So we could implement the same steps, if the view touchEvent method returns false or the evt has been stopped, the gestureManager must not bubble up.

I don't know if i could be missing something or being wrong with this approach, suggestions are wellcome, @jschilli  let me know, if you want to Pull Request against master including some unit Tests.

**Comment by ppcano** [comment]
Your second option has been included in the following [commit](https://github.com/emberjs-addons/sproutcore-touch/commit/cdb9b55cd33c54263557ab496b6e789d6e9967b6). 

I am closing this issue.
